apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acm-demo-mobility
resources:
- ../../base
replicas:
- name: catalog
  count: 2
- name: order-quote
  count: 2
- name: storefront
  count: 2
