apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources.yaml
configMapGenerator:
- name: retail-code
  files:
  - server.py
  - index.html
generatorOptions:
  disableNameSuffixHash: true
  labels:
    demo.acm.example.com/id: aro-retail
