apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acm-demo-dev
resources:
- ../../base
replicas:
- name: catalog
  count: 1
- name: order-quote
  count: 1
- name: storefront
  count: 1
