apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  labels:
    app.kubernetes.io/part-of: dispatch-desk
  namespace: openshift-gitops
spec:
  clusterSet: default
